# Generated by Django 5.0 on 2023-12-18 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('audi', 'Ауди'), ('bmw', 'БМВ'), ('honda', 'Хонда'), ('mazda', 'Мазда'), ('mercedes', 'Мерседес'), ('nissan', 'Ниссан'), ('toyota', 'Тойота')], max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('steering', models.CharField(choices=[('left', 'Левосторонний'), ('right', 'Правосторонний')], max_length=10)),
                ('mileage', models.IntegerField()),
                ('transmission', models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('robot', 'Робот')], max_length=10)),
                ('drive', models.CharField(choices=[('front', 'Передний'), ('rear', 'Задний'), ('4wd', '4 WD')], max_length=10)),
                ('fuel', models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ'), ('electric', 'Электро')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
