# Generated by Django 5.0 on 2023-12-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='image',
            field=models.ImageField(blank=True, upload_to='car_images/'),
        ),
    ]
