# Generated by Django 5.0 on 2023-12-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0002_alter_avto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='image',
            field=models.ImageField(blank=True, upload_to='avtoimg/%Y/%m/%d'),
        ),
    ]
