# Generated by Django 5.0 on 2023-12-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0003_alter_avto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
