# Generated by Django 5.0 on 2023-12-20 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0004_alter_avto_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='avto',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avto',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
