# Generated by Django 4.1.13 on 2023-12-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0005_avto_created_avto_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='avto',
            name='city',
            field=models.CharField(default='Krasnoyarsk', max_length=50),
            preserve_default=False,
        ),
    ]
